spring.datasource.url: ${JDBC_DATABASE_URL}
spring.datasource.username: ${JDBC_DATABASE_USERNAME}
spring.datasource.password: ${JDBC_DATABASE_PASSWORD}

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update # update: don't drop, create: drop

